spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/user_db'
    password: 'root'
    username: 'root'

  profiles:
    include:
      - properties

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql

  sql:
    init:
      mode: always

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
