CREATE TABLE IF NOT EXISTS user_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255),
    address      VARCHAR(255),
    birth_date   date                                    NOT NULL,
    CONSTRAINT pk_user_info PRIMARY KEY (id)
);