version: '3.3'

networks:
  webshot:

services:
  postgres:
    image: postgres:14
    container_name: clear-solution-test-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - clear-solution-test:/var/lib/postgresql

volumes:
  clear-solution-test:

